title: Shantanu Saxena
logo: /assets/img/shantanu-saxena.jpeg
description: I am currently learning ie; doing second Masters in Machine learning and Artificial Intelligence 
  and this is going to be my first project to work on. Though from last 9 years i am working 
  as Sr. UX/UI Researcher, Designer & Developer. My First Masters was in Advanced Computer Science 
  in HMI & HCI.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
